steps:
# Step 1: Initialize Terraform
# This step downloads the necessary providers and configures the GCS backend.
- name: 'hashicorp/terraform:1.8.0'
  entrypoint: 'terraform'
  args: ['init']

# Step 2: Run Terraform Plan
# This step creates an execution plan and uses the prj.tfvars file for variables.
- name: 'hashicorp/terraform:1.8.0'
  entrypoint: 'terraform'
  args: ['apply',  '-auto-approve']

logsBucket: gs://jason-hsbc_cloudbuild/logs/
options: # https://cloud.google.com/cloud-build/docs/build-config#options
  logging: GCS_ONLY # or CLOUD_LOGGING_ONLY https://cloud.google.com/cloud-build/docs/build-config#logging

serviceAccount: 'projects/jason-hsbc/serviceAccounts/terraform@jason-hsbc.iam.gserviceaccount.com'
